version: "3"

services:
    rproxy:
        image: nginx:latest
        container_name: rproxy_dyn
        volumes:
            - ./conf:/etc/nginx
        ports:
            - "8080:80"
        restart: always
        networks:
          - net-rproxy

    nginx:
        depends_on:
            - rproxy
        image: api/nginx
        container_name: nginx
        build:
            context: ../step3/
        restart: always
        networks:
          - net-rproxy

    express:
        depends_on:
            - rproxy
        image: api/express
        container_name: express
        build:
            context: ../step4/
        restart: always
        networks:
          - net-rproxy

networks:
    net-rproxy:

